[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "froth"
authors = [{name = "TaTooKa", email = "leandro.rolando@gmail.com"}]
dynamic = ["version", "description"]
